### ISSUE TITLE
Creazione del wireframe del modello "Calendario"

### ISSUE THREAD

**Issue by EnigmaEdivad** [scuoleparrocchialidesio/www#10]

**Comment by EnigmaEdivad** [comment]
Mobile: https://ibb.co/XVRcKD2

**Comment by olistik** [comment]
Non tutti gli eventi potrebbero essere dotati di cover.
Prevediamolo.

**Comment by EnigmaEdivad** [comment]
Tolgo direttamente quindi?

**Comment by olistik** [comment]
Meglio prevedere che alcuni li abbiano e altri no.

**Comment by EnigmaEdivad** [comment]
quindi ne faccio due? Una versione con e l'altra senza?

**Comment by olistik** [comment]
No, una versione sola con alcuni progetti dotati di cover e alcuni senza. Se possibile, intervallati fra di loro. Per esempio 1 con, 2 senza e 1 con.

**Comment by EnigmaEdivad** [comment]
Ok

**Comment by EnigmaEdivad** [comment]
Mobile: https://ibb.co/Kw5NVhV
Così?

**Comment by olistik** [comment]
Ho solo il dubbio se lo stacco tra i singoli progetti sia sufficiente o se serva rafforzarlo in qualche modo ma mi sembra che già così funzioni abbastanza bene. 👍

**Comment by EnigmaEdivad** [comment]
Produco anche la versione desktop quindi?

**Comment by EnigmaEdivad** [comment]
https://ibb.co/gW8CMRY

**Comment by olistik** [comment]
Nel caso desktop sarebbe utile provare ad introdurre una visualizzazione più densa.

Fai una pensata sulla base di questi esempi:

<img width="395" alt="Screenshot 2019-03-20 at 15 15 34" src="https://user-images.githubusercontent.com/21038/54692214-ed151b00-4b24-11e9-8ac4-9a262541fe4f.png">
<img width="356" alt="Screenshot 2019-03-20 at 15 15 44" src="https://user-images.githubusercontent.com/21038/54692215-edadb180-4b24-11e9-9756-a4ffdd5d4763.png">
<img width="597" alt="Screenshot 2019-03-20 at 15 17 08" src="https://user-images.githubusercontent.com/21038/54692216-edadb180-4b24-11e9-9bdf-2f9607ded7fe.png">
<img width="593" alt="Screenshot 2019-03-20 at 15 18 26" src="https://user-images.githubusercontent.com/21038/54692217-edadb180-4b24-11e9-8a38-159ead80e504.png">
<img width="583" alt="Screenshot 2019-03-20 at 15 18 34" src="https://user-images.githubusercontent.com/21038/54692218-edadb180-4b24-11e9-9637-8cda392afdb3.png">
<img width="587" alt="Screenshot 2019-03-20 at 15 18 41" src="https://user-images.githubusercontent.com/21038/54692219-edadb180-4b24-11e9-8b80-a9d09b77a40c.png">

**Comment by olistik** [comment]
@EnigmaEdivad il commento https://github.com/scuoleparrocchialidesio/www/issues/16#issuecomment-474859601 è pertinente anche a questa issue.

**Comment by EnigmaEdivad** [comment]
Quindi rifaccio ma senza immagini e sulla versione desktop invece una versione "Time line"

**Comment by olistik** [comment]
@EnigmaEdivad Sì, togli le immagini.
Mentre ripensi al wireframe desktop in modalità timeline e/o con [card](https://material.io/design/components/cards.html) cerca di capire se e in caso come ci sono elementi che potrebbero essere portati anche in mobile.

**Comment by EnigmaEdivad** [comment]
Bhe, se si utilizzasse la versione con card non andrebbe bene utilizzarla anche su mobile?

**Comment by EnigmaEdivad** [comment]
Come rich media si posso utilizzare due icone che simboleggiano pedagogico e amministrazione

**Comment by olistik** [comment]
> Bhe, se si utilizzasse la versione con card non andrebbe bene utilizzarla anche su mobile?

Esattamente.
Cerca di considerare le card e il concetto di timeline come ispirazioni.
Non ti sto dicendo di usare solo uno o per forza tutti e due.

Per esempio, nel mobile si potrebbe tenere una linea verticale laterale rappresentante il tempo, con dei punti in prossimità degli eventi (con o senza card a supporto) mentre nel desktop, la linea temporale potrebbe essere portata nel centro, o dividendo la pagina in due, con le card che si alternano ai lati, oppure congiungendo un evento con l'altro (senza quindi essere una linea continua).

**Comment by olistik** [comment]
> Come rich media si posso utilizzare due icone che simboleggiano pedagogico e amministrazione

L'uso di icone, come di colori del testo/sfondo, è una buona idea come anche affiancargli una rappresentazione testuale, in ottica di accessibilità dei contenuti.

Qui, intanto, altri esempi di card: https://getbootstrap.com/docs/4.3/components/card/

**Comment by EnigmaEdivad** [comment]
mobile: https://ibb.co/c6d3kBR

**Comment by olistik** [comment]
> mobile: https://ibb.co/c6d3kBR

Bello. 🎩 

L'unico dubbio è relativo alla dimensione/posizionamento dell'icona ma possiamo delegare questo dettaglio visuale alla fase di implementazione dello statico, contesto in cui dovremmo effettuare il design del componente.
Potremmo anche arrivare a decidere di rimuovere completamente l'icona o anche solo di usare l'icona a discapito del testo.

A questo punto resta da capire come far evolvere il design su desktop.

**Comment by EnigmaEdivad** [comment]
Timeline in mezzo, così da formare due colonne e a capo di esse icona e descrizione della rispettiva categoria?

**Comment by olistik** [comment]
Ha senso. 👍 
Attento all'importanza della data.
Per consistenza con il mobile ti consiglierei di metterla in evidenza sulla timeline.
In caso dovessi fare economia di spazio puoi spostare icona e categoria dentro la card.

**Comment by EnigmaEdivad** [comment]
E se la mettesssi al posto del pallino?

**Comment by olistik** [comment]
Non male.
In seguito sarà interessante capire come visualizzarlo in armonia (per esempio, racchiuso in un bordo?) ma per ora va bene.

**Comment by EnigmaEdivad** [comment]
https://ibb.co/jDD7HzR

**Comment by olistik** [comment]
Oh, non avevo compreso che volessi creare due tracce distinte.
Dopo un po' di esitazione ti dico che mi piace.

**Comment by olistik** [comment]
@EnigmaEdivad Ho avuto un ripensamento. Se c'è un'asimmetria tra il numero o anche solo la distribuzione di una categoria di eventi, la timeline presenta contesti visivi con metà schermo vuoto.
Dovremmo invece implementare un design che permette la presenza di queste asimmetrie di contenuto.
Suppongo che una opzione adeguata (non l'unica) sia mostrare gli eventi in sequenza, a prescindere dalla loro categoria.

**Comment by EnigmaEdivad** [comment]
Appena torno a casa provvedo.

**Comment by EnigmaEdivad** [comment]
1: https://ibb.co/JsTMjdF
2: https://ibb.co/tqGdycv
@olistik So che forse non va bene ma ci provo

**Comment by olistik** [comment]
Innanzitutto complimenti per entrambi gli esperimenti.
Sono interessanti ma temo che per questo contesto soffrano di due problemi:

1. viene posta troppa attenzione alla categoria
2. il posizionamento della data non crea una forte associazione con l'evento. A mio parere appesantisce un po' la fruizione da parte del visitatore perché gli richiede una maggiore attenzione nel capire quale sia la data dell'evento.

Mi piace molto la versione con la linea orizzontale, perché non sfruttarla per farle contenere data e categoria? In questo modo risolveremmo entrambi i punti.

<img width="571" alt="Screenshot 2019-03-21 at 17 37 04" src="https://user-images.githubusercontent.com/21038/54768825-51f17380-4c00-11e9-8789-0fce8d2aca8d.png">

N.B.: sia questi ultimi esperimenti che la timeline con suddivisione verticale restano ottimi per altri contesti 🎩 .
Ora stiamo raffinando gli schemi visuali fino a trovare una composizione ottimale al nostro caso. :-)

**Comment by EnigmaEdivad** [comment]
https://ibb.co/9ZgZHZZ
Che ne pensi di questa?

**Comment by olistik** [comment]
Molto, molto bella.
Posizionare l'icona sulla sinistra è un'ottima idea.
Complimenti. 🎩

**Comment by EnigmaEdivad** [comment]
Metto nell'altro repository?

**Comment by olistik** [comment]
Un consiglio, in seguito carica le immagini direttamente qua come allegato, invece che inserire il link, così evitiamo che i link scadano.

**Comment by EnigmaEdivad** [comment]
Va bene
