### ISSUE TITLE
Design dell'header, footer e struttura generica delle pagine (wireframe)

### ISSUE THREAD

**Issue by olistik** [scuoleparrocchialidesio/www#11]

**Comment by EnigmaEdivad** [comment]
Desktop: https://ibb.co/6PghFzk

@olistik, per il mobile teniamo quello che ho proposto nella issue della Homepage?

**Comment by olistik** [comment]
@EnigmaEdivad 

> Desktop: https://ibb.co/6PghFzk

👍 

> @olistik, per il mobile teniamo quello che ho proposto nella issue della Homepage?

Direi di no, abbiamo solo 3 link e i breadcrumb da mostrare.
Quasi non servirebbe neanche l'hamburger icon.
Se però vuoi tenerla, ricorda anche l'ipotesi dell'overlay fullscreen.

**Comment by olistik** [comment]
Infine, nel footer non è meglio tenere gli elementi centrati?
Vuoi che resti tutto lo spazio vuoto centrale?

**Comment by olistik** [comment]
Dobbiamo poi salvare i wireframe che mano a mano vengono accettati.

Crea un repository chiamato _design_ che conterrà almeno gli asset (come i wireframe) che andremo a produrre.

**Comment by EnigmaEdivad** [comment]
> Direi di no, abbiamo solo 3 link e i breadcrumb da mostrare.
Quasi non servirebbe neanche l'hamburger icon.
Se però vuoi tenerla, ricorda anche l'ipotesi dell'overlay fullscreen.

Non saprei, se la togliessimo non saprei come risolvere il problema di dover mostrare l'elenco delle scuole se si clicca su "Le scuole"

**Comment by EnigmaEdivad** [comment]
> Infine, nel footer non è meglio tenere gli elementi centrati?
> Vuoi che resti tutto lo spazio vuoto centrale?

Ok, li centro

**Comment by EnigmaEdivad** [comment]
> Dobbiamo poi salvare i wireframe che mano a mano vengono accettati.
> 
> Crea un repository chiamato _design_ che conterrà almeno gli asset (come i wireframe) che andremo a produrre.

Un repository diverso da questo? O una cartella all'interno di questo progetto?

**Comment by olistik** [comment]
> Non saprei, se la togliessimo non saprei come risolvere il problema di dover mostrare l'elenco delle scuole se si clicca su "Le scuole"

Possiamo aprire una pagina con il semplice elenco delle 3 scuole.

**Comment by olistik** [comment]
> > Dobbiamo poi salvare i wireframe che mano a mano vengono accettati.
> > Crea un repository chiamato _design_ che conterrà almeno gli asset (come i wireframe) che andremo a produrre.
> 
> Un repository diverso da questo? O una cartella all'interno di questo progetto?

Sì, diverso perché questo è il repository che viene ricostruito ad ogni push e dovremmo cercare di tenerlo il più possibile snello.

**Comment by EnigmaEdivad** [comment]
> > > Dobbiamo poi salvare i wireframe che mano a mano vengono accettati.
> > > Crea un repository chiamato _design_ che conterrà almeno gli asset (come i wireframe) che andremo a produrre.
> > 
> > 
> > Un repository diverso da questo? O una cartella all'interno di questo progetto?
> 
> Sì, diverso perché questo è il repository che viene ricostruito ad ogni push e dovremmo cercare di tenerlo il più possibile snello.

Ok, faccio subito

**Comment by EnigmaEdivad** [comment]
> > Non saprei, se la togliessimo non saprei come risolvere il problema di dover mostrare l'elenco delle scuole se si clicca su "Le scuole"
> 
> Possiamo aprire una pagina con il semplice elenco delle 3 scuole.

Quindi un modello apposta per il mobile?

**Comment by olistik** [comment]
> > > Non saprei, se la togliessimo non saprei come risolvere il problema di dover mostrare l'elenco delle scuole se si clicca su "Le scuole"
> > 
> > 
> > Possiamo aprire una pagina con il semplice elenco delle 3 scuole.
> 
> Quindi un modello apposta per il mobile?

E uno per il desktop.
Crea la issue apposita.

Secondo me può essere una pagina molto semplice con un elenco verticale di titolo + immagine + link "accedi". Questo elenco parte come lista verticale nel caso mobile e può diventare un elenco orizzontale su desktop.
Che ne dici?

**Comment by EnigmaEdivad** [comment]
> > > > Non saprei, se la togliessimo non saprei come risolvere il problema di dover mostrare l'elenco delle scuole se si clicca su "Le scuole"
> > > 
> > > 
> > > Possiamo aprire una pagina con il semplice elenco delle 3 scuole.
> > 
> > 
> > Quindi un modello apposta per il mobile?
> 
> E uno per il desktop.
> Crea la issue apposita.
> 
> Secondo me può essere una pagina molto semplice con un elenco verticale di titolo + immagine + link "accedi". Questo elenco parte come lista verticale nel caso mobile e può diventare un elenco orizzontale su desktop.
> Che ne dici?

Va bene

**Comment by EnigmaEdivad** [comment]
Desktop: https://ibb.co/ZN2tD7D
Mobile: https://ibb.co/L80M8yt

**Comment by olistik** [comment]
@EnigmaEdivad Bravòh!

Noto che hai optato per gestire il footer in due righe, interessante.

E complimenti per la gestione dell'header su mobile, mi piace che sia disposto su due righe. Inizialmente avevo pensato ad avere una riga per ogni link ma la tua soluzione mi sembra migliorativa.

Appena le metti sul nuovo repository chiudi pure questa issue.

**Comment by EnigmaEdivad** [comment]
Provvedo
