### ISSUE TITLE
Creazione wireframe del modello "Le scuole"

### ISSUE THREAD

**Issue by EnigmaEdivad** [scuoleparrocchialidesio/www#12]

**Comment by EnigmaEdivad** [comment]
Desktop: https://ibb.co/4fsp8Fk
Mobile: https://ibb.co/FhvSFk3

**Comment by olistik** [comment]
LGTM!

**Comment by olistik** [comment]
@EnigmaEdivad Ricordati di inserire i wireframe nel repository _design_.

**Comment by EnigmaEdivad** [comment]
Dimenticato di pushare
