### ISSUE TITLE
Creazione di tutte le issue necessarie

### ISSUE THREAD

**Issue by olistik** [scuoleparrocchialidesio/www#13]

**Comment by EnigmaEdivad** [comment]
@olistik Adesso dovrebbero esserci tuttte, ne ho dimenticate qualcuna?

**Comment by olistik** [comment]
@EnigmaEdivad 

1. Definizione della palette, con inserimento nella style guide
2. Definizione della tipografia, con inserimento nella style guide
3. Produzione dello statico della griglia generale (header + footer) con comportamento responsive
4. Produzione dello statico della pagina X (una issue per ogni wireframe creato in precedenza)
5. Creazione dei modelli DatoCMS
6. Integrazione DatoCMS

I punti 3. e 4. comporteranno l'aggiornamento della style guide con l'inserimento dei componenti mano a mano identificati.

**Comment by EnigmaEdivad** [comment]
Ok, le aggiungo subito

**Comment by olistik** [comment]
@EnigmaEdivad Suppongo siano state inserite tutte. 🙂
