### ISSUE TITLE
Creazione del wireframe del modello "Progetti in corso"

### ISSUE THREAD

**Issue by EnigmaEdivad** [scuoleparrocchialidesio/www#14]

**Comment by EnigmaEdivad** [comment]
Com'è?
Mobile: https://ibb.co/9n8WMG6

**Comment by olistik** [comment]
@EnigmaEdivad Nei breadcrumbs manca il nome della scuola.
La paginazione dovrebbe comprendere anche i link "first" e "last".
Ok per il resto. :-)

**Comment by EnigmaEdivad** [comment]
Ok, provvedo

**Comment by EnigmaEdivad** [comment]
Mobile: https://ibb.co/Qmdj0Fp
Desktop: https://ibb.co/ynz3g41

**Comment by olistik** [comment]
Nel mobile manca ancora il nome dell'asilo nei breadcrumbs. 🤓

**Comment by olistik** [comment]
Mettilo ed è a posto. :-)

**Comment by EnigmaEdivad** [comment]
https://ibb.co/93Bds4y
