### ISSUE TITLE
Creazione del wireframe del singolo progetto

### ISSUE THREAD

**Issue by EnigmaEdivad** [scuoleparrocchialidesio/www#15]

**Comment by EnigmaEdivad** [comment]
Serviva anche un link al pdf della descrizione completa del progetto vero?

https://ibb.co/BjKVtZm

**Comment by olistik** [comment]
Mmh, non lo ricordo.
Penso di no ma chiediamo pure nel forum.

**Comment by olistik** [comment]
Il progetto non comprendeva anche una galleria di immagini?

**Comment by EnigmaEdivad** [comment]
> Il progetto non comprendeva anche una galleria di immagini?

Provvedo

**Comment by EnigmaEdivad** [comment]
mobile: https://ibb.co/7XW8CSd

**Comment by EnigmaEdivad** [comment]
desktop: 
https://ibb.co/dKL05P8

**Comment by olistik** [comment]
LGTM!
