### ISSUE TITLE
Creazione del wireframe del singolo evento

### ISSUE THREAD

**Issue by EnigmaEdivad** [scuoleparrocchialidesio/www#16]

**Comment by EnigmaEdivad** [comment]
Anche in questo c'è bisogno della galleria?

**Comment by olistik** [comment]
@EnigmaEdivad Per risponderti ho colto l'occasione per rivedere gli appunti presi e mi sono reso conto che per il calendario degli eventi (e quindi anche per gli eventi) non abbiamo menzionato l'uso delle immagini, quindi non serve mostrarle.

## Pagina Scuola > Eventi

- Quando (indicazione temporale scritta in testo in forma libera)
- Descrizione
- Titolo
- Categoria: “Amministrativo” o “Pedagogico”

E questo vale anche per il calendario eventi dell'esploratorio.

**Comment by EnigmaEdivad** [comment]
mobile: https://ibb.co/m97Dyrm
desktop: https://ibb.co/QMDRtKv

**Comment by olistik** [comment]
Easy peasy. LGTM.
