### ISSUE TITLE
Definizione della palette, con inserimento nella style guide

### ISSUE THREAD

**Issue by EnigmaEdivad** [scuoleparrocchialidesio/www#18]

**Comment by EnigmaEdivad** [comment]
Ci ho provato

![gg](https://user-images.githubusercontent.com/45203239/55172391-4959e980-517a-11e9-93e6-cc06ba2c65ee.png)

**Comment by EnigmaEdivad** [comment]
![33](https://user-images.githubusercontent.com/45203239/55287548-a2a85f80-53aa-11e9-9080-a201b4c5e7a3.png)

**Comment by olistik** [comment]
@EnigmaEdivad Attenzione, non avevamo deciso di puntare su un tema bianco e nero?

<img width="319" alt="Screenshot 2019-04-17 at 18 07 27" src="https://user-images.githubusercontent.com/21038/56303227-c524d180-613b-11e9-8a02-224f44c66143.png">

**Comment by olistik** [comment]
@EnigmaEdivad Nel frattempo, butta un occhio a questo esperimento (ridimensionando la finestra) e dimmi se la consideri una buona integrazione:

https://codepen.io/olistik/pen/oOEdjQ

**Comment by EnigmaEdivad** [comment]
ok, applico. Per i link invece che faccio?

**Comment by olistik** [comment]
> ok, applico. Per i link invece che faccio?

Rimuovi i colori attuali dei link e ripensa a come vuoi stilizzare i link/bottoni.
Eventualmente potrebbe richiedere l'integrazione della palette.
Penso che si debbano aggiungere nuove gradazioni di B/N oppure prendere colori pre-esistenti e nella descrizione definire che si applicano anche ai link (e in caso come).

**Comment by EnigmaEdivad** [comment]
E se rendessimo i bottoni a loro volta utilizzabili anche per i link? Un bottone anche per la funzione "scarica" in poche parole

**Comment by olistik** [comment]
@enigmaedivad

> E se rendessimo i bottoni a loro volta utilizzabili anche per i link? Un bottone anche per la funzione scarica in poche parole

Promuovere link isolati a bottoni è fattibile ma restano comunque eventuali link presenti nei blocchi di testo. È difficile trasformare in grazia questi link in bottoni.
Penso che dovremmo comunque prevedere uno stile B/N anche per i link non bottoni.

**Comment by EnigmaEdivad** [comment]
OK, creo una pull request con i nuovi possibili colori per solo i link?

**Comment by olistik** [comment]
@EnigmaEdivad 

> OK, creo una pull request con i nuovi possibili colori per solo i link?

Sì, rimuovendo anche gli attuali link "colorati" dei link. 👍

**Comment by olistik** [comment]
@EnigmaEdivad Ho mergiato le modifiche. Durante la review mi è sfuggito un problema che è venuto alla luce dopo il deploy:

<img width="1169" alt="Screenshot 2019-04-18 at 13 01 25" src="https://user-images.githubusercontent.com/21038/56356843-3dda6b00-61da-11e9-8f56-e3a47d33fa97.png">

Serve che ogni elemento contenga anche la classe `palette-color` in modo che erediti il comportamento comune ad ogni `palette-color` e non solo quello della variante.

**Comment by EnigmaEdivad** [comment]
pusho le modifiche direttamente?

**Comment by olistik** [comment]
> pusho le modifiche direttamente?

Meglio andare di PR.
