### ISSUE TITLE
Definizione della tipografia, con inserimento nella style guide

### ISSUE THREAD

**Issue by EnigmaEdivad** [scuoleparrocchialidesio/www#19]

**Comment by olistik** [comment]
Una fonte di font gratuiti molto interessanti: https://www.fontsquirrel.com/fonts/list/popular

**Comment by EnigmaEdivad** [comment]
Non vanno bene quei duei che ho scelto?

**Comment by olistik** [comment]
Mmh, su quale repository hai pushato il codice? :-)

**Comment by EnigmaEdivad** [comment]
Style guide, dove mi avevi detto no? Inviato dal mio dispositivo mobile Huawei-------- Messaggio originale --------Oggetto: Re: [scuoleparrocchialidesio/www] Definizione della tipografia, con inserimento nella style guide (#19)Da: olistik A: scuoleparrocchialidesio/www CC: EnigmaEdivad ,Author Mmh, su quale repository hai pushato il codice? :-)

**Comment by olistik** [comment]
@EnigmaEdivad Eh ma non ci sono i commit: https://github.com/scuoleparrocchialidesio/style-guide/commits/master 😅

**Comment by EnigmaEdivad** [comment]
Provvedo...

**Comment by olistik** [comment]
@EnigmaEdivad Ok, direi che questa è a posto.

I font che hai scelto:

- [Bitter](https://fonts.google.com/specimen/Bitter)
- [Libre Baskerville](https://fonts.google.com/specimen/Libre+Baskerville)

Il risultato è visibile nella style guide: https://style-guide-site.netlify.com
