### ISSUE TITLE
Integrazione tra il repository GitHub e Netlify

### ISSUE THREAD

**Issue by EnigmaEdivad** [scuoleparrocchialidesio/www#2]

**Comment by olistik** [comment]
@EnigmaEdivad Manca di inserire l'indirizzo del sito.

**Comment by olistik** [comment]
Per completezza, aggiorna anche le informazioni del repository (tasto edit):

<img width="1035" alt="Screenshot 2019-03-11 at 15 54 50" src="https://user-images.githubusercontent.com/21038/54133284-142d6780-4416-11e9-83f6-77c70a4a0a9f.png">

**Comment by olistik** [comment]
> Per completezza, aggiorna anche le informazioni del repository (tasto edit):
> 
> <img alt="Screenshot 2019-03-11 at 15 54 50" width="1035" src="https://user-images.githubusercontent.com/21038/54133284-142d6780-4416-11e9-83f6-77c70a4a0a9f.png">

@EnigmaEdivad ricorda questa indicazione.

**Comment by EnigmaEdivad** [comment]
Cosa devo mettere lì?

**Comment by olistik** [comment]
Sito web e descrizione di massima.

**Comment by EnigmaEdivad** [comment]
Va bene?

**Comment by olistik** [comment]
> Va bene?

L'ho rinominato in _Gruppo Scuole Parocchiali di Desio_.
Ricorda che anche questo repository è un contesto con cui l'ente comunica in prima persona.
Al termine del lavoro ne sposteremo il possesso al cliente.

**Comment by EnigmaEdivad** [comment]
Capito
