### ISSUE TITLE
Produzione dello statico della griglia generale (header + footer) con comportamento responsive

### ISSUE THREAD

**Issue by EnigmaEdivad** [scuoleparrocchialidesio/www#20]

**Comment by olistik** [comment]
@EnigmaEdivad Questa issue è ok.
Il comportamento responsive è ottimo.
Per ora nessun breakpoint ma solo ridimensionamento fluido.
Il footer sta in fondo anche quando non c'è contenuto e scorre naturalmente in base alla presenza del contenuto.

<img width="501" alt="Screenshot 2019-04-16 at 11 47 32" src="https://user-images.githubusercontent.com/21038/56199598-83adfc80-603d-11e9-9161-a7cdf9718188.png">
<img width="499" alt="Screenshot 2019-04-16 at 11 47 44" src="https://user-images.githubusercontent.com/21038/56199599-83adfc80-603d-11e9-8066-9f5a4b7912fb.png">
<img width="1222" alt="Screenshot 2019-04-16 at 11 47 56" src="https://user-images.githubusercontent.com/21038/56199600-83adfc80-603d-11e9-818e-5bf198a5ffc1.png">
