### ISSUE TITLE
Modello calendario della sezione "Esploratori"

### ISSUE THREAD

**Issue by EnigmaEdivad** [scuoleparrocchialidesio/www#32]

**Comment by EnigmaEdivad** [comment]
Mobile
![calendario](https://user-images.githubusercontent.com/45203239/54815889-3d11f000-4c93-11e9-9e56-c8ec5fd6c58b.png)

**Comment by olistik** [comment]
@EnigmaEdivad In generale, unire più eventi sotto la stessa data è un'idea interessante. Temo che non potremo applicarla nel nostro caso, dato che le date degli eventi non sono omogenee come struttura.
Va comunque bene il design mobile. 👍

**Comment by EnigmaEdivad** [comment]
Come mi consigli di procedere allora?

**Comment by olistik** [comment]
Basterebbe avere un pallino con data per ogni evento.

**Comment by EnigmaEdivad** [comment]
> Basterebbe avere un pallino con data per ogni evento.

Solo nel desktop?

**Comment by olistik** [comment]
Mi riferivo al mobile ma anche nel desktop non possiamo raggruppare più eventi sotto la stessa data.
Semplicemente più eventi potrebbero avere la stessa data.

**Comment by EnigmaEdivad** [comment]
capito

**Comment by EnigmaEdivad** [comment]
![esp m](https://user-images.githubusercontent.com/45203239/54818568-dc39e600-4c99-11e9-9188-aabf066fdc81.png)

**Comment by EnigmaEdivad** [comment]
![esp d](https://user-images.githubusercontent.com/45203239/54818614-fd9ad200-4c99-11e9-920a-ec88717bb93d.png)

**Comment by EnigmaEdivad** [comment]
![esp d](https://user-images.githubusercontent.com/45203239/54818718-2d49da00-4c9a-11e9-8d26-cbc7c0f7e377.png)

**Comment by olistik** [comment]
Purrfect. 👍

**Comment by olistik** [comment]
Tra l'altro, complimenti per la scelta delle icone. Mi paiono azzeccate. 🎩

**Comment by EnigmaEdivad** [comment]
Ottimo
