### ISSUE TITLE
Modello evento singolo del calendario della sezione esploratori

### ISSUE THREAD

**Issue by EnigmaEdivad** [scuoleparrocchialidesio/www#33]

**Comment by EnigmaEdivad** [comment]
![evento m](https://user-images.githubusercontent.com/45203239/54822724-d6e29880-4ca5-11e9-92f4-c57196144154.png)
![evento d](https://user-images.githubusercontent.com/45203239/54822725-d77b2f00-4ca5-11e9-8b79-386f6a7944d0.png)

**Comment by olistik** [comment]
Non inseriamo anche l'icona della categoria?

**Comment by EnigmaEdivad** [comment]
Nell'altro non le avevamo messe quindi pensavo che bisognasse mantenere la stessa linearità, provvedo

**Comment by olistik** [comment]
Buona considerazione.
Nell'altro caso mi era sfuggito.
Penso che mostrare l'icona anche nella pagina di dettaglio aiuti a mantenere una consistenza visuale.
Potremmo cominciare a metterla in piccolo, ai lati del nome della categoria ma non escludo che possano esserci altre combinazioni più interessanti.
Per favore, una volta deciso come gestire qui l'icona, aggiorna anche il dettaglio dell'evento per l'altro wireframe.
Per il resto il design è ok.

**Comment by EnigmaEdivad** [comment]
![evento d](https://user-images.githubusercontent.com/45203239/54823105-1958a500-4ca7-11e9-8241-2058e7889fce.png)
![evento m](https://user-images.githubusercontent.com/45203239/54823106-19f13b80-4ca7-11e9-84e9-2238fb19ae97.png)

**Comment by olistik** [comment]
I dettagli visuali della zona sopra il titolo (e magari compreso il titolo) potrebbero modificare posizionamento e dimensione di data, categoria, icona e titolo ma per ora penso che il wireframe sia più che adeguato. 👍

**Comment by EnigmaEdivad** [comment]
Cambio quindi anche gli altri seguendo questo modello?

**Comment by olistik** [comment]
Sì.
