### ISSUE TITLE
Creazione del wireframe del modello "Homepage"

### ISSUE THREAD

**Issue by EnigmaEdivad** [scuoleparrocchialidesio/www#4]

**Comment by EnigmaEdivad** [comment]
Mobile: https://ibb.co/2g9Q3S4
@olistik

**Comment by EnigmaEdivad** [comment]
Desktop: https://ibb.co/K6Tcr1j

Su questo sono indeciso sul design dell'Header. Nel caso andasse bene, è meglio questo oppure come quello del tema (https://html5up.net/telephasic) in desktop mode?

**Comment by olistik** [comment]
<img width="1433" alt="Screenshot 2019-03-10 at 18 55 51" src="https://user-images.githubusercontent.com/21038/54089147-2c45ae00-4366-11e9-9cc1-7a3854e020d6.png">

**Comment by olistik** [comment]
È stata creata una issue specifica per definire il comportamento generale del tema.

#11

**Comment by EnigmaEdivad** [comment]
Desktop 1: https://ibb.co/wMsBbsp
Desktop 2: https://ibb.co/Q6WyQkH
Mobile: https://ibb.co/tpVmrnk

**Comment by olistik** [comment]
@EnigmaEdivad Nel mobile metterei comunque le sezioni del calendario e della scuola in chiaro, a scopo di promozione di quei contenuti.

Lato desktop, hai deciso di sfasare volutamente quelle due voci?
Attento che non sono link diretti a dei PDF ma dei link a delle pagine.
Ti consiglio di usare una generica immagine per dire che vuoi affiancargli un elemento visuale.

Riguardo alla versione desktop 2 e più in generale, penso che la presenza/natura di un separatore tra sezioni sia più responsabilità del design successivo e non del wireframe. Per ora concentriamoci solo sul contenuto.

**Comment by EnigmaEdivad** [comment]
> @EnigmaEdivad Nel mobile metterei comunque le sezioni del calendario e della scuola in chiaro, a scopo di promozione di quei contenuti.

Pensavo ci fossimo messi d'accordo per evitare di ripeterle da mobile, sistemo

**Comment by EnigmaEdivad** [comment]
> Lato desktop, hai deciso di sfasare volutamente quelle due voci?
> Attento che non sono link diretti a dei PDF ma dei link a delle pagine.
> Ti consiglio di usare una generica immagine per dire che vuoi affiancargli un elemento visuale.

Sì, le ho sfalsate volontariamente, per evitare di renderlo un semplice elenco. Non va bene?
Nel sito che utilizzo non c'è una icona che si riferisce ad un documento, quindi ho usato quella ma lo so che si riferisce a dei modelli

**Comment by EnigmaEdivad** [comment]
> Riguardo alla versione desktop 2 e più in generale, penso che la presenza/natura di un separatore tra sezioni sia più responsabilità del design successivo e non del wireframe. Per ora concentriamoci solo sul contenuto.

Ok

**Comment by olistik** [comment]
> > @EnigmaEdivad Nel mobile metterei comunque le sezioni del calendario e della scuola in chiaro, a scopo di promozione di quei contenuti.
> 
> Pensavo ci fossimo messi d'accordo per evitare di ripeterle da mobile, sistemo

Avevo frainteso. 😅

**Comment by EnigmaEdivad** [comment]
Desktop: https://ibb.co/vJCMSTJ
Mobile: https://ibb.co/W3wNf1M

**Comment by olistik** [comment]
@enigmaedivad Nella versione mobile mancano i primi 2 contenuti.

**Comment by EnigmaEdivad** [comment]
Mobile: https://ibb.co/bdwN5pS

**Comment by olistik** [comment]
LGTM!

**Comment by olistik** [comment]
@EnigmaEdivad Scusa, riapro.
Chiudi appena hai salvato i wireframe nel repository _design_.
