### ISSUE TITLE
Creazione del wireframe del modello "Scuola in chiaro"

### ISSUE THREAD

**Issue by EnigmaEdivad** [scuoleparrocchialidesio/www#5]

**Comment by EnigmaEdivad** [comment]
Per quest'ultimo wireframe basta una serie di documenti divisi a seconda della scuola?

**Comment by olistik** [comment]
No, meglio ancora, basta una semplice lista di documenti con link per il download, titolo e una breve descrizione.

**Comment by olistik** [comment]
La lista è unica per tutte le scuole.

**Comment by EnigmaEdivad** [comment]
![scuola in chiaro](https://user-images.githubusercontent.com/45203239/54838943-14591d00-4cca-11e9-8eaf-54beb48ad328.png)

![scuola](https://user-images.githubusercontent.com/45203239/54839061-5aae7c00-4cca-11e9-83d7-d91b9617def8.png)

**Comment by olistik** [comment]
Vince. 👍

**Comment by olistik** [comment]
🤔

Ho dato un'occhiata alla documentazione di DatoCMS e abbiamo accesso a 3 informazioni:

- data di creazione
- data di pubblicazione (la data della prima pubblicazione)
- data di aggiornamento

Penso sia sensato aggiungere almeno la data di pubblicazione e la data di aggiornamento.
Non ordineremo questi documenti per queste date, dato che l'ordinamento sarà deciso manualmente.

Possiamo inserire le due date dentro le card.

**Comment by EnigmaEdivad** [comment]
> 🤔
> 
> Ho dato un'occhiata alla documentazione di DatoCMS e abbiamo accesso a 3 informazioni:
> 
>     * data di creazione
> 
>     * data di pubblicazione (la data della prima pubblicazione)
> 
>     * data di aggiornamento
> 
> 
> Penso sia sensato aggiungere almeno la data di pubblicazione e la data di aggiornamento.
> Non ordineremo questi documenti per queste date, dato che l'ordinamento sarà deciso manualmente.
> 
> Possiamo inserire le due date dentro le card.

Una sotto al titolo e l'altra  sopra il link per scaricare il documento?

**Comment by olistik** [comment]
Ok, mi pare sensato. :thumbsup:

**Comment by EnigmaEdivad** [comment]
![prototipo](https://user-images.githubusercontent.com/45203239/54879731-c7e21e80-4e3c-11e9-922f-755da4e96ec5.png)
![prototipo 2](https://user-images.githubusercontent.com/45203239/54879732-c7e21e80-4e3c-11e9-98cf-639e62198206.png)

**Comment by olistik** [comment]
Pubblicato il.
Comunque ok.

**Comment by EnigmaEdivad** [comment]
Non ti convince?

**Comment by olistik** [comment]
No, no, mi convince.
L'unico appunto è sul fatto di usare "Pubblicato il" invece di "Creato il".
Per il resto mi pare che vada bene.

**Comment by EnigmaEdivad** [comment]
![2](https://user-images.githubusercontent.com/45203239/54880313-c700bb00-4e43-11e9-8745-53a23719060a.png)
![1](https://user-images.githubusercontent.com/45203239/54880314-c700bb00-4e43-11e9-8342-c6753f627ccc.png)

**Comment by olistik** [comment]
👍

**Comment by olistik** [comment]
@EnigmaEdivad Se l'hai concluso (comprensivo di inserimento dei wireframe nel repository), chiudilo e spostalo in Done.
