### ISSUE TITLE
Creazione del wireframe del modello "Esploratori"

### ISSUE THREAD

**Issue by EnigmaEdivad** [scuoleparrocchialidesio/www#9]

**Comment by EnigmaEdivad** [comment]
Qui il per il calendario come dovrei fare? Metto solamente delle card?

**Comment by olistik** [comment]
Riprendo gli appunti (con una piccola integrazione).

## Esploratori

- Descrizione
- Foto Gallery
- Team (foto + testo)

## Esploratori > Calendario

- Quando (indicazione temporale scritta in testo in forma libera)
- Descrizione
- Titolo

3 tipi di eventi:

- Esploratori
- Genitorialità
- Mamme in gravidanza

Quindi questo wireframe dovrebbe contenere la descrizione, una foto gallery, team e il link al calendario.

Serve una issue per il wireframe della pagina "Esploratori > Calendario" e conseguentemente una issue per il wireframe della pagina "Esploratori > Calendario > Evento".

**Comment by EnigmaEdivad** [comment]
OK, meglio così.

**Comment by EnigmaEdivad** [comment]
Mobile
![Esploratori](https://user-images.githubusercontent.com/45203239/54814688-87de3880-4c90-11e9-8f3f-800be966af39.png)

**Comment by EnigmaEdivad** [comment]
Desktop
![esploratori dek](https://user-images.githubusercontent.com/45203239/54815192-adb80d00-4c91-11e9-9048-f7b831b5c204.png)

**Comment by olistik** [comment]
@EnigmaEdivad Su desktop, "team" e "calendario" non potrebbero diventare card che occupano metà dello spazio a disposizione?

**Comment by EnigmaEdivad** [comment]
Provvedo

**Comment by EnigmaEdivad** [comment]
![cal](https://user-images.githubusercontent.com/45203239/54818451-90873c80-4c99-11e9-85a5-a95c4764e1ae.png)

**Comment by EnigmaEdivad** [comment]
@olistik, mi potresti dare una conferma riguardo l'ultima modifica?

**Comment by olistik** [comment]
Ti avevo messo il pollice alto ma effettivamente meglio la conferma testuale.
Va bene. :-)

**Comment by EnigmaEdivad** [comment]
> Ti avevo messo il pollice alto ma effettivamente meglio la conferma testuale.
> Va bene. :-)

Sorry, non me lo mostrava.
